### PR TITLE
Workaround timeout

### LINKED ISSUE #31: Tests flaking under heavy CPU load
Thanks @tumido! 
Tested. All test cases work as expected, except these 2:

```bash
Thoth Station miminal Python 3.8   This image is expected to PASS validation   Failed
                                   false
                                   [{"severity":"error","message":"start-singleuser.sh script took too long to call 'jupyter labhub'"}]
```
```bash
Thoth Station miminal Python 3.8   This image is expected to PASS validation   Failed
                                   false
                                   [{"severity":"error","message":"start-singleuser.sh script took too long to call 'jupyter labhub'"}]
```

_Originally posted by @oindrillac in https://github.com/open-services-group/byon/pull/29#pullrequestreview-917729830_

### PR DESCRIPTION
**Pull request by tumido**
Depends on #35 (merge after)

Resolves: https://github.com/open-services-group/byon/issues/31

### CODE REVIEW

**Review by oindrillac — COMMENTED** [review]
/lgtm

**Comment by tumido** [comment]
/hold

wait for #35

**Comment by codificat** [comment]
> @oindrillac: changing LGTM is restricted to collaborators

feel free to contribute to https://github.com/thoth-station/core/blob/486cf548ad1b5279448aa262d2d9db453ce08d3f/community/github-config.yaml#L19

**Comment by oindrillac** [comment]
> feel free to contribute to https://github.com/thoth-station/core/blob/486cf548ad1b5279448aa262d2d9db453ce08d3f/community/github-config.yaml#L19

Done https://github.com/thoth-station/core/pull/395 , thanks @codificat

**Comment by codificat** [comment]
/approve
feel free to unhold when #35 merges

**Pull request merged**
