### PR TITLE
Use a microshift cluster for chart testing

### PR DESCRIPTION
**Pull request by codificat**
This sets up a [microshift](https://microshift.io) cluster with Tekton to test the charts during PRs.

Also, the chart does not include the service account referenced by the event listener or associated RBAC. Changing the EventListener to use the `pipeline` service account provided by the Tekton operator.

### CODE REVIEW

**Comment by codificat** [comment]
/hold a bit

tests are green now but flaky, only need to improve cluster readyness checks

**Comment by codificat** [comment]
ok, tests are looking better now,
/unhold

Note that this PR also modifies #18 to use the `pipeline` service account (provided by tekton-operator) instead of providing one in the chart.

@harshad16 can you PTAL?

**Review by harshad16 — COMMENTED** [review]
lgtm :+1:

**Comment by codificat** [comment]
/approve
let's get it in

**Pull request merged**
